//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject_EntityFramework_WindowsForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbSchoolStudentEntities : DbContext
    {
        public DbSchoolStudentEntities()
            : base("name=DbSchoolStudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLGRADES> TBLGRADES { get; set; }
        public virtual DbSet<TBLLECTURES> TBLLECTURES { get; set; }
        public virtual DbSet<TBLSTUDENT> TBLSTUDENT { get; set; }
    
        public virtual ObjectResult<GRADELIST_Result> GRADELIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRADELIST_Result>("GRADELIST");
        }
    }
}
