//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject_EntityFramework_WindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGRADES
    {
        public int GRADEID { get; set; }
        public Nullable<int> STD { get; set; }
        public Nullable<int> LECTURE { get; set; }
        public Nullable<short> EXAM1 { get; set; }
        public Nullable<short> EXAM2 { get; set; }
        public Nullable<short> EXAM3 { get; set; }
        public Nullable<decimal> AVERAGE { get; set; }
        public Nullable<bool> STATE { get; set; }
    
        public virtual TBLLECTURES TBLLECTURES { get; set; }
        public virtual TBLSTUDENT TBLSTUDENT { get; set; }
    }
}
